[package]
name = "almel"
version = "0.1.0"
authors = ["Ryooooooga <ryoga_314@yahoo.co.jp>"]
description = "A ZSH theme inspired by agnoster-zsh-theme"
edition = "2018"

[dependencies]
clap = "2.33.0"
failure = "0.1.6"
