[package]
name = "almel"
version = "1.1.5"
authors = ["Ryooooooga <ryoga_314@yahoo.co.jp>"]
description = "A ZSH theme inspired by agnoster-zsh-theme"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Ryooooooga/almel"
keywords = ["zsh", "prompt"]
edition = "2018"

[dependencies]
chrono = "0.3.0"
dirs = "2.0"
failure = "0.1.6"
hostname = "0.2"
git2 = "0.10"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
structopt = "0.3.3"

[target.'cfg(not(windows))'.dependencies]
users = "0.9.1"
